CREATE OR REPLACE FUNCTION st_contains as 'com.azavea.hiveless.spatial.index.ST_Contains';
CREATE OR REPLACE FUNCTION st_crsFromText as 'com.azavea.hiveless.spatial.index.ST_CrsFromText';
CREATE OR REPLACE FUNCTION st_extentFromGeom as 'com.azavea.hiveless.spatial.index.ST_ExtentFromGeom';
CREATE OR REPLACE FUNCTION st_extentToGeom as 'com.azavea.hiveless.spatial.index.ST_ExtentToGeom';
CREATE OR REPLACE FUNCTION st_geomReproject as 'com.azavea.hiveless.spatial.index.ST_GeomReproject';
CREATE OR REPLACE FUNCTION st_intersects as 'com.azavea.hiveless.spatial.index.ST_Intersects';
CREATE OR REPLACE FUNCTION st_makeExtent as 'com.azavea.hiveless.spatial.index.ST_MakeExtent';
CREATE OR REPLACE FUNCTION st_partitionCentroid as 'com.azavea.hiveless.spatial.index.ST_PartitionCentroid';
CREATE OR REPLACE FUNCTION st_z2LatLon as 'com.azavea.hiveless.spatial.index.ST_Z2LatLon';
